<a href="https://colab.research.google.com/github/clionelove123/temp_test/blob/main/Chap_01_Introduction_to_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Pytorch Tutorial (reference - https://github.com/GunhoChoi/PyTorch-FastCampus)

# 1. Hello World!
print("Hello World!")

Hello World!


In [2]:
# 2. Variables and Types
a = 2
print(a,type(a),end="\n\n")

b = 2.0
print(b,type(b),end="\n\n")

c = "Pytorch"
print(c,type(c),end="\n\n")

d = a+b
print(d,type(d),end="\n\n")

e = str(a)+" "+c
print(e,type(e),end="\n\n")

2 <class 'int'>

2.0 <class 'float'>

Pytorch <class 'str'>

4.0 <class 'float'>

2 Pytorch <class 'str'>



In [3]:
# 3. Arithmetic Operations
a=1
b=2
c=3

print(a+b)
print(a-b)
print(b*c)
print(b/c)
print(c//b)
print(b**c)

3
-1
6
0.6666666666666666
1
8


In [4]:
# 4. List
list_1 = [1,2,3]
print(list_1)

list_1.append(4)
print(list_1)

list_1.append("abc")
print(list_1)

# index
print(list_1[:-1])

del list_1[-1]
print(list_1)

list_1.pop()
print(list_1)

[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 'abc']
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3]


In [5]:
# 5. Dictionary
dict_1 = {
    "python": 0,
    "java":1,
    "c++":2,
    "ruby":3,
    "html":4,
    "key":"value",
}

print(dict_1)
print(dict_1["c++"])

del dict_1["key"]
print(dict_1)

dict_1["pytorch"]=5
print(dict_1)

{'python': 0, 'java': 1, 'c++': 2, 'ruby': 3, 'html': 4, 'key': 'value'}
2
{'python': 0, 'java': 1, 'c++': 2, 'ruby': 3, 'html': 4}
{'python': 0, 'java': 1, 'c++': 2, 'ruby': 3, 'html': 4, 'pytorch': 5}


In [6]:
# 6. Loop
for i in range(5):
    print(i)

print("\n")
for i in range(0,-5,-1):
    print(i)


print(list_1)
for i in list_1:
    print(i)

print("\n")
print(dict_1)
for key in dict_1:
    print(key,dict_1[key])

a=0
while(a<10):
    print(a)
    a+=1

0
1
2
3
4


0
-1
-2
-3
-4
[1, 2, 3]
1
2
3


{'python': 0, 'java': 1, 'c++': 2, 'ruby': 3, 'html': 4, 'pytorch': 5}
python 0
java 1
c++ 2
ruby 3
html 4
pytorch 5
0
1
2
3
4
5
6
7
8
9


In [7]:
# 7. Condition

print(2==2)
print(2==3)
print(2!=2)
print(2!=3)

print(dict_1)
for key in dict_1:
    if key=="ruby":
        print(dict_1[key])
    else:
        print("not ruby")

True
False
False
True
{'python': 0, 'java': 1, 'c++': 2, 'ruby': 3, 'html': 4, 'pytorch': 5}
not ruby
not ruby
not ruby
3
not ruby
not ruby


In [8]:
# 8. Function
def factorial(num):
    result = 1
    for i in range(1,num+1):
        result = result*i
    return result

print(factorial(5))


120


In [9]:
# 9. Class and Objects
class Jedi(object):
    def __init__(self,name,droid):
        self.name = name
        self.droid = droid
        self.exp = 0
        
    def train(self):
        self.exp += 10

anakin = Jedi("Anakin Skywalker","R2D2")
anakin.train()

print(anakin.name)
print(anakin.droid)
print(anakin.exp)

Anakin Skywalker
R2D2
10


In [10]:
# 1. Create Tensor
# 1) random numbers
import torch

# torch.rand(sizes) -> [0,1)
x = torch.rand(2,3)
x

# torch.randn(sizes) -> Z(0,1)
x = torch.randn(2,3)
x

# torch.randperm(n) -> permutation of 0~n
x = torch.randperm(5)
x

tensor([0, 3, 2, 1, 4])

In [11]:
# 2) zeros, ones, arange
# torch.zeros(2,3) -> [[0,0,0],[0,0,0]]
x = torch.zeros(2,3)
x

# torch.ones(2,3) -> [[0,0,0],[0,0,0]]
x = torch.ones(2,3)
x

# torch.arange(start,end,step=1) -> [start,end) with step
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [12]:
# 3) Tensor Data Type
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
x

# torch.FloatTensor(size or list)
x = torch.FloatTensor([2,3])
x

# tensor.type_as(tensor_type)
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

In [13]:
# 4) Numpy to Tensor, Tensor to Numpy
import numpy as np

# torch.from_numpy(ndarray) -> tensor

x1 = np.ndarray(shape=(2,3), dtype=int,buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)

x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# tensor.numpy() -> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 5) Tensor Size
# tensor.size() -> indexing also possible

x = torch.FloatTensor(10,12,3,3)

x.size()[:]

torch.Size([10, 12, 3, 3])

In [16]:
# 2. Indexing, Slicing, Joining
# 1) Indexing
# torch.index_select(input, dim, index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))

x,out

(tensor([[0.1983, 0.6842, 0.4393],
         [0.4426, 0.5025, 0.7378],
         [0.6388, 0.6165, 0.8146],
         [0.5219, 0.9894, 0.2873]]),
 tensor([[0.1983, 0.6842, 0.4393],
         [0.5219, 0.9894, 0.2873]]))

In [17]:
# pythonic indexing also works

x[:,0],x[0,:],x[0:2,0:2]

(tensor([0.1983, 0.4426, 0.6388, 0.5219]),
 tensor([0.1983, 0.6842, 0.4393]),
 tensor([[0.1983, 0.6842],
         [0.4426, 0.5025]]))

In [18]:
# torch.masked_select(input, mask)

x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)

x, mask, out

<ipython-input-18-0672fe6d8568>:5: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1855.)
  out = torch.masked_select(x,mask)


(tensor([[-0.6715,  0.3081, -0.4824],
         [-1.0169,  0.6840, -1.1993]]),
 tensor([[0, 0, 1],
         [0, 1, 0]], dtype=torch.uint8),
 tensor([-0.4824,  0.6840]))

In [19]:
# 2) Joining
# torch.cat(seq, dim=0) -> concatenate tensor along dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

x,y,z1,z2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [20]:
# torch.stack(sequence,dim=0) -> stack along new dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack = torch.stack([x,x,x,x],dim=0)

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

In [21]:
# 3) Slicing
# torch.chunk(tensor, chunks, dim=0) -> tensor into num chunks

x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

z1,x_1,x_2,z1,y_1,y_2,y_3

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]),
 tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [22]:
# torch.split(tensor,split_size,dim=0) -> split into specific size

x1,x2 = torch.split(z1,2,dim=0)
y1 = torch.split(z1,2,dim=1) 

z1,x1,x2,y1

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 (tensor([[ 1.,  2.],
          [ 4.,  5.],
          [-1., -2.],
          [-4., -5.]]),
  tensor([[ 3.],
          [ 6.],
          [-3.],
          [-6.]])))

In [23]:
# 4) squeezing
# torch.squeeze(input,dim=None) -> reduce dim by 1

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(),x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [24]:
# torch.unsqueeze(input,dim=None) -> add dim by 1

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x1.size(),x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

In [25]:
# 3. Initialization
import torch.nn.init as init

x1 = init.uniform(torch.FloatTensor(3,4),a=0,b=9) 
x2 = init.normal(torch.FloatTensor(3,4),std=0.2)
x3 = init.constant(torch.FloatTensor(3,4),3.1415)

x1,x2,x3

<ipython-input-25-a21abc297f1c>:4: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  x1 = init.uniform(torch.FloatTensor(3,4),a=0,b=9)
<ipython-input-25-a21abc297f1c>:5: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  x2 = init.normal(torch.FloatTensor(3,4),std=0.2)
<ipython-input-25-a21abc297f1c>:6: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  x3 = init.constant(torch.FloatTensor(3,4),3.1415)


(tensor([[5.5719, 2.4182, 1.7198, 8.8860],
         [0.1632, 0.7380, 3.7046, 0.6786],
         [2.3794, 5.1846, 7.4282, 4.3600]]),
 tensor([[ 0.1870, -0.2559,  0.1840, -0.1535],
         [ 0.1381,  0.2436,  0.3475, -0.3286],
         [ 0.3347, -0.1882,  0.0044,  0.3419]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))

In [26]:
# 4. Math Operations
# 1) Arithmetic operations
# torch.add()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

print("1:",x1," \n",x2," \n",add," \n",x1+x2," \n",x1-x2)

# torch.add() broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10)

print("2:",x1," \n",x2," \n",x1+10," \n",x2-10)

# torch.mul() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

print("3:",x1," \n",x2," \n",x3)

# torch.mul() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = x1*10

print("4:",x1," \n",x2)

# torch.div() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

print("5:",x1," \n",x1/5)

1: tensor([[1., 2., 3.],
        [4., 5., 6.]])  
 tensor([[1., 2., 3.],
        [4., 5., 6.]])  
 tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])  
 tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])  
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
2: tensor([[1., 2., 3.],
        [4., 5., 6.]])  
 tensor([[11., 12., 13.],
        [14., 15., 16.]])  
 tensor([[11., 12., 13.],
        [14., 15., 16.]])  
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
3: tensor([[1., 2., 3.],
        [4., 5., 6.]])  
 tensor([[1., 2., 3.],
        [4., 5., 6.]])  
 tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
4: tensor([[1., 2., 3.],
        [4., 5., 6.]])  
 tensor([[10., 20., 30.],
        [40., 50., 60.]])
5: tensor([[1., 2., 3.],
        [4., 5., 6.]])  
 tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])


In [27]:
# 2) Other Math Operations
# torch.pow(input,exponent)

x1 = torch.rand(3,4)
print("1: ", x1,"\n",torch.pow(x1,2),"\n",x1**2)

# torch.exp(tensor,out=None) 

x1 = torch.rand(3,4)
print("2: ",x1,"\n",torch.exp(x1))

# torch.log(input, out=None) -> natural logarithm

x1 = torch.rand(3,4)
print("3: ",x1,"\n",torch.log(x1))

1:  tensor([[0.4176, 0.7183, 0.4903, 0.4450],
        [0.4809, 0.2831, 0.5603, 0.6927],
        [0.7693, 0.7175, 0.6362, 0.8070]]) 
 tensor([[0.1744, 0.5160, 0.2404, 0.1980],
        [0.2312, 0.0801, 0.3140, 0.4799],
        [0.5919, 0.5148, 0.4048, 0.6513]]) 
 tensor([[0.1744, 0.5160, 0.2404, 0.1980],
        [0.2312, 0.0801, 0.3140, 0.4799],
        [0.5919, 0.5148, 0.4048, 0.6513]])
2:  tensor([[0.5695, 0.8921, 0.8312, 0.9589],
        [0.8265, 0.7983, 0.6999, 0.8085],
        [0.6671, 0.5425, 0.1671, 0.1005]]) 
 tensor([[1.7674, 2.4404, 2.2961, 2.6089],
        [2.2853, 2.2218, 2.0135, 2.2446],
        [1.9485, 1.7204, 1.1818, 1.1057]])
3:  tensor([[0.6112, 0.3205, 0.7528, 0.8620],
        [0.8151, 0.0948, 0.8275, 0.4687],
        [0.7674, 0.6661, 0.3318, 0.4688]]) 
 tensor([[-0.4924, -1.1380, -0.2840, -0.1485],
        [-0.2044, -2.3563, -0.1894, -0.7577],
        [-0.2648, -0.4063, -1.1032, -0.7577]])


In [28]:
# 3) Matrix operations
# torch.mm(mat1, mat2) -> matrix multiplication


x1 = torch.rand(4,3)
x2 = torch.rand(3,5)

print("1: ",x1,"\n",x2,"\n",torch.mm(x1,x2))

# torch.bmm(batch1, batch2) -> batch matrix multiplication

x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)

print("2: ",torch.bmm(x1,x2).size())

# torch.dot(tensor1,tensor2) -> dot product of two tensor

x1 = torch.rand(4)
x2 = torch.rand(4)

print("3: ",x1,"\n",x2,"\n",torch.dot(x1,x2))

# torch.t(matrix) -> transposed matrix

x1 = torch.FloatTensor(3,4)

print("4: ",x1,"\n",x1.t())

# torch.transpose(input,dim0,dim1) -> transposed matrix

x1 = torch.FloatTensor(10,3,4)

print("5: ",x1.size(),"\n", torch.transpose(x1,1,2).size(),"\n", x1.transpose(1,2).size())

# torch.eig(a,eigenvectors=False) -> eigen_value, eigen_vector
x1 = torch.rand(4,4)

print("6: ",x1,"\n",torch.linalg.eig(x1))

1:  tensor([[0.8986, 0.0124, 0.9570],
        [0.6027, 0.0111, 0.2603],
        [0.8406, 0.2045, 0.5141],
        [0.2383, 0.4980, 0.7315]]) 
 tensor([[0.0738, 0.0849, 0.7851, 0.0912, 0.7439],
        [0.1965, 0.0641, 0.2870, 0.8354, 0.4750],
        [0.7352, 0.7523, 0.0221, 0.2097, 0.6997]]) 
 tensor([[0.7724, 0.7970, 0.7302, 0.2930, 1.3439],
        [0.2380, 0.2477, 0.4821, 0.1189, 0.6358],
        [0.4802, 0.4712, 0.7300, 0.3554, 1.0822],
        [0.6533, 0.6024, 0.3461, 0.5912, 0.9256]])
2:  torch.Size([10, 3, 5])
3:  tensor([0.3702, 0.6427, 0.2973, 0.8505]) 
 tensor([0.2877, 0.7927, 0.1267, 0.3084]) 
 tensor(0.9159)
4:  tensor([[-7.0374e-30,  4.5680e-41,  9.4428e-35,  0.0000e+00],
        [ 4.4842e-44,  0.0000e+00,  1.1210e-43,  0.0000e+00],
        [ 9.4437e-35,  0.0000e+00,  0.0000e+00,  0.0000e+00]]) 
 tensor([[-7.0374e-30,  4.4842e-44,  9.4437e-35],
        [ 4.5680e-41,  0.0000e+00,  0.0000e+00],
        [ 9.4428e-35,  1.1210e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+

In [29]:
# 1.Import Required Libraries

import torch
from torch.autograd import Variable

In [30]:
# 2. Tensor vs Variable
# 1) Declaration
x_tensor = torch.Tensor(3,4)
x_tensor

tensor([[1.2139e-37, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 9.4067e-35, 0.0000e+00],
        [7.1218e+08, 4.5680e-41, 9.4067e-35, 0.0000e+00]])

In [31]:
x_variable = Variable(x_tensor)
x_variable

tensor([[1.2139e-37, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 9.4067e-35, 0.0000e+00],
        [7.1218e+08, 4.5680e-41, 9.4067e-35, 0.0000e+00]])

In [32]:
# 2) Variables of a Variable
# .data -> wrapped tensor 
x_variable.data

tensor([[1.2139e-37, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 9.4067e-35, 0.0000e+00],
        [7.1218e+08, 4.5680e-41, 9.4067e-35, 0.0000e+00]])

In [33]:
# .grad -> gradient of the variable
print(x_variable.grad)

None


In [34]:
# .requires_grad -> whether variable requres gradient
print(x_variable.requires_grad)

x_variable = Variable(x_tensor,requires_grad=True)
x_variable.requires_grad

False


True

In [35]:
# .volatile -> inference mode with minimal memory usage
# single volatile variable makes whole graph not requiring gradient

x_variable = Variable(x_tensor,volatile=True)
x_variable.grad, x_variable.requires_grad, x_variable.volatile

<ipython-input-35-e6ef0bcb7d2c>:4: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x_variable = Variable(x_tensor,volatile=True)
<ipython-input-35-e6ef0bcb7d2c>:5: UserWarning: volatile was removed (Variable.volatile is always False)
  x_variable.grad, x_variable.requires_grad, x_variable.volatile


(None, False, False)

In [36]:
# 3. Graph & Variables

# create graph

x = Variable(torch.FloatTensor(3,4),requires_grad=True)
y = x**2 + 4*x
z = 2*y +3

x.requires_grad,y.requires_grad,z.requires_grad

(True, True, True)

In [37]:
# .backward(gradient,retain_graph,create_graph,retain_variables)
# compute gradient of current variable w.r.t. graph leaves

loss = torch.FloatTensor(3,4)
z.backward(loss)

print(x.grad)
y.grad,z.grad

tensor([[-5.6300e-29,  3.6544e-40,  7.5230e-34,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.9063e+00,  6.1642e+32,  5.7718e+23]])


<ipython-input-37-353e1b0fe3a2>:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  y.grad,z.grad


(None, None)