<a href="https://colab.research.google.com/github/clionelove123/temp_test/blob/main/Chap_3_linear_regression_modified.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# -*- coding: utf-8 -*-
import tensorflow as tf

print(tf.__version__)


2.11.0


In [ ]:
@tf.function
def linear_model(x_1,x_2,x_3):
  return W_1*x_1 + W_2* x_2 + W_3* x_3 +b


x_1=10
x_2=12
x_3=15

# 선형회귀 모델(Wx + b)을 위한 tf.Variable을 선언합니다.
W_1 = tf.Variable(tf.random.normal(shape=[1]))
W_2 = tf.Variable(tf.random.normal(shape=[1]))
W_3 = tf.Variable(tf.random.normal(shape=[1]))
b = tf.Variable(tf.random.normal(shape=[1]))


# 손실 함수를 정의합니다.
# MSE 손실함수 \mean{(y' - y)^2}
@tf.function
def mse_loss(y_pred, y):
  return tf.reduce_mean(tf.square(y_pred - y))

In [ ]:
# 트레이닝을 위한 입력값과 출력값을 준비합니다.


x_1_train=[7.2, 9.9, 4.7, 0.5]
x_2_train=[2.2,5.4,2.1,6.5]
x_3_train=[4.2,7.4,1.1,9.5]
y_train=[33.7, 38.1, 21.3, 0.6]




In [ ]:
y_pred = linear_model(x_1_train,x_2_train,x_3_train)

loss = mse_loss(y_pred, y_train)

print("1: ",y_pred.numpy())

print("2: ",loss.numpy())

1:  [-20.285732 -35.35712   -8.788162 -31.548613]
2:  2562.3098


In [ ]:
# 최적화를 위한 그라디언트 디센트 옵티마이저를 정의합니다.
optimizer = tf.optimizers.SGD(0.01)

# 최적화를 위한 function을 정의합니다.
@tf.function
def train_step(x1,x2,x3, y):
  with tf.GradientTape() as tape:
    y_pred = linear_model(x1,x2,x3)
    loss = mse_loss(y_pred, y)
  gradients = tape.gradient(loss, [W_1,W_2,W_3, b])
  optimizer.apply_gradients(zip(gradients, [W_1,W_2,W_3, b]))

In [ ]:
# 경사하강법을 1000번 수행합니다.

for i in range(1000):
  train_step(x_1_train,x_2_train,x_3_train, y_train)
  if i<10:
    k=tf.convert_to_tensor([W_1.numpy(),W_2.numpy(),W_3.numpy(),b.numpy()])
    print(k.numpy())
  else:
    if (i%100)<1:
      k=tf.convert_to_tensor([W_1.numpy(),W_2.numpy(),W_3.numpy(),b.numpy()])
      print(k.numpy())

[[5.229497 ]
 [2.9475043]
 [2.7846   ]
 [2.6221979]]
[[ 1.2421737]
 [-0.543067 ]
 [-2.1596558]
 [ 1.9073266]]
[[5.009796 ]
 [1.8751214]
 [1.264189 ]
 [2.4828877]]
[[ 2.5313115 ]
 [-0.22012615]
 [-1.6870482 ]
 [ 2.0509279 ]]
[[4.7719393 ]
 [1.2572975 ]
 [0.41969824]
 [2.4012606 ]]
[[ 3.2408547 ]
 [-0.00591385]
 [-1.3458245 ]
 [ 2.1412365 ]]
[[ 4.5787473 ]
 [ 0.8921653 ]
 [-0.05235744]
 [ 2.355422  ]]
[[ 3.6372757 ]
 [ 0.12686414]
 [-1.1097037 ]
 [ 2.1998296 ]]
[[ 4.4387145 ]
 [ 0.66956747]
 [-0.31619674]
 [ 2.331678  ]]
[[ 3.8618076 ]
 [ 0.20308304]
 [-0.94927394]
 [ 2.2394905 ]]
[[ 4.165463  ]
 [-0.5692271 ]
 [-0.11787836]
 [ 2.8391223 ]]
[[ 4.1398735 ]
 [-1.1574205 ]
 [ 0.22137806]
 [ 3.4861429 ]]
[[ 4.108606  ]
 [-1.515505  ]
 [ 0.40903166]
 [ 4.096772  ]]
[[ 4.077731 ]
 [-1.7584039]
 [ 0.5246907]
 [ 4.6444893]]
[[ 4.0494947]
 [-1.9385076]
 [ 0.604019 ]
 [ 5.124426 ]]
[[ 4.024526  ]
 [-2.0805323 ]
 [ 0.66332215]
 [ 5.5402226 ]]
[[ 4.0027966]
 [-2.1968176]
 [ 0.7103309]
 [ 5.898421 ]]

In [ ]:
# 테스트를 위한 입력값을 준비합니다.
x_1_test = [0,10,20,30]
x_2_test = [5,15,25,35]
x_3_test = [12,25,31,75]

print(linear_model(x_1_test,x_2_test,x_3_test).numpy())




[  4.1665435  29.760616   49.69587   100.35046  ]
