<a href="https://colab.research.google.com/github/clionelove123/temp_test/blob/main/Chap_3_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# -*- coding: utf-8 -*-

import pathlib

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import math

import numpy as np

print(tf.__version__)


2.11.0


In [3]:
@tf.function
def linear_model(x):
  return W*x + b

x=10

# 선형회귀 모델(Wx + b)을 위한 tf.Variable을 선언합니다.
W = tf.Variable(tf.random.normal(shape=[1]))
b = tf.Variable(tf.random.normal(shape=[1]))

k=tf.convert_to_tensor([W.numpy(),b.numpy()])
print(k.numpy())

# 손실 함수를 정의합니다.
# MSE 손실함수 \mean{(y' - y)^2}
@tf.function
def mse_loss(y_pred, y):
  return tf.reduce_mean(tf.square(y_pred - y))

[[-0.67133343]
 [ 0.48718837]]


In [4]:
# 트레이닝을 위한 입력값과 출력값을 준비합니다.

x_train=[7.2, 9.9, 4.7, 0.5]
y_train=[33.7, 38.1, 21.3, 0.6]

#x_train=[6.6, 3.5, 1.4, 3.5, 7.6, 7.3, 0.6, 9.5, 4.1, 0.6, 0.6, 3.1, 1, 0.7, 9.8, 0.5, 4.2, 8.7, 5, 8.5, 5.8, 8.6, 0.2, 5.2, 8.7, 3.2, 9.6, 3.2, 5.3, 7.8, 7.7, 9.7, 6.4, 7.4, 2.4, 2.9, 2.3, 6.8, 1.8, 6, 7.3, 8.8, 8.2, 5.9, 1.9, 3.1, 8.8, 6.9, 4, 1.3]
#y_train=[26.3, 16.5, 7.7, 14.8, 30.9, 29, 5.8, 37.3, 17.3, 5.4, 4.5, 13.4, 6.2, 4.9, 39.6, 4.3, 18.8, 35.5, 20.8, 34.8, 23.4, 35.4, 3.2, 21.6, 34.1, 14, 38.9, 14.2, 21.6, 31.8, 32.1, 38.3, 25.8, 31.1, 10.7, 12.8, 11.7, 28.7, 10.4, 25.8, 29.8, 35.1, 32.7, 24.7, 10.2, 14.9, 35.5, 27.5, 17, 8.5]



In [5]:
y_pred = linear_model(x_train)

loss = mse_loss(y_pred, y_train)

print(y_pred.numpy())
print(loss.numpy())

[-4.346412   -6.1590123  -2.6680787   0.15152165]
995.2649


In [6]:
# 최적화를 위한 그라디언트 디센트 옵티마이저를 정의합니다.
optimizer = tf.optimizers.SGD(0.01)

# 최적화를 위한 function을 정의합니다.
@tf.function
def train_step(x, y):
  with tf.GradientTape() as tape:
    y_pred = linear_model(x)
    loss = mse_loss(y_pred, y)
  gradients = tape.gradient(loss, [W, b])
  optimizer.apply_gradients(zip(gradients, [W, b]))

In [7]:
# 경사하강법을 1000번 수행합니다.

for i in range(100):
  train_step(x_train, y_train)
  if i<10:
#    z=linear_model(x)
#    k=tf.convert_to_tensor([W.numpy(),b.numpy(),z.numpy()])
    k=tf.convert_to_tensor([W.numpy(),b.numpy()])
    print(k.numpy())
  else:
    if (i%10)<1:
#      z=linear_model(x)
#      k=tf.convert_to_tensor([W.numpy(),b.numpy(),z.numpy()])
#      print(k.numpy())
      k=tf.convert_to_tensor([W.numpy(),b.numpy()])
      print(k.numpy())



[[3.4535294]
 [1.0207982]]
[[3.9675944]
 [1.0838138]]
[[4.0320487]
 [1.0882508]]
[[4.0405164]
 [1.0854123]]
[[4.0420103]
 [1.0816865]]
[[4.0426335]
 [1.0778686]]
[[4.0431457]
 [1.0740576]]
[[4.043642 ]
 [1.0702657]]
[[4.0441337]
 [1.0664942]]
[[4.044623 ]
 [1.0627434]]
[[4.045109 ]
 [1.0590131]]
[[4.049827 ]
 [1.0228139]]
[[4.0542936 ]
 [0.98854584]]
[[4.0585213 ]
 [0.95610565]]
[[4.0625243 ]
 [0.92539626]]
[[4.066313  ]
 [0.89632523]]
[[4.0698996 ]
 [0.86880517]]
[[4.073295  ]
 [0.84275335]]
[[4.07651   ]
 [0.81809133]]


In [8]:
# 테스트를 위한 입력값을 준비합니다.
x_test = [0,10,20,30]

print(linear_model(x_test).numpy())




[  0.7970226  41.58958    82.38213   123.17469  ]
